package org.game;

public enum MagicElement {
    FIRE, ICE, WATER, WIND, ELECTRIC, EARTH, VEGETAL, ANIMAL, BLOOD, DIVINATION, SHAMANISM, SHADOW, PSYCHICH, MOVEMENT,
    SUMMON, REGENARATION, EVIL, NECROMANCY, ILLUSION, UNIQUE, TIME, LIFE, DEATH
}
